### ISSUE TITLE
The Demo is offline.

### ISSUE THREAD

**Issue by Jieiku** [elegaanz/zola-theme-course#1]
The Demo is offline.

You could host the demo on Netlify or github pages so that you never need to worry about it being offline.

**Comment by Jieiku** [comment]
How do you feel about setting up a netlify account to automatically build a demo of the theme? It is actually really easy, only takes a few minutes.

If this is not something your interested in doing, would you like me to create a mirror of the repository and create a demo that way?

**Comment by Jieiku** [comment]
Could also just use github.io for the demo, I just like netlify because they give you the ability to set your headers.

**Comment by elegaanz** [comment]
I fixed it!
